name: flutter_onboarding
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  rect_getter: ^0.0.1
  gradient_text: ^1.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
   - assets/illustration.png
   - assets/illustration2.png
   - assets/illustration3.png

fonts:
  - family: Montserrat-Black
    fonts:
      - asset: assets/Montserrat-Black.ttf

  - family: Montserrat-Medium
    fonts:
      - asset: assets/Montserrat-Medium.ttf
